### PR TITLE
Update to avalonia-rc1.1

### PR DESCRIPTION
**Pull request by ArchLeaders**
- Replace AvaloniaLocator DI with simple Shared instance

### CODE REVIEW

**Comment by halgari** [comment]
Any word on if/when this might be updated? I have a project we need to update to RC1 to get some bug fixes in, and we need to get this to be merged so we can get our app to work.

**Comment by cyraid** [comment]
@ArchLeaders @SebastianRumohr I wonder if this would break compatibility? Though people using an old Avalonia, could just lock their version anyway until 11 stable comes out? Would probably need a version bump with this?

**Comment by SebastianRumohr** [comment]
I will work on this issue today. I'll merge this pr right away and change some more things. A new version should be available today.
@cyraid all versions targeting Avalonia 11 are already a new major version (see: https://www.nuget.org/packages/Projektanker.Icons.Avalonia/#versions-body-tab)

**Comment by SebastianRumohr** [comment]
The new version [6.6.0-rc1.1](https://www.nuget.org/packages/Projektanker.Icons.Avalonia/6.6.0-rc1.1) is available.  
⚠️ The registration changed. You have to register the icon provider directly with the `IconProvider.Current`.
See here: https://github.com/Projektanker/Icons.Avalonia/tree/avalonia-11-preview#1-register-icon-providers-on-app-start-up

**Comment by cyraid** [comment]
> Any reason for removing the `WithIcons` extension, rather than just marking it obsolete (or just leaving it)?

I agree. Kinda looks awkward now, I liked it before with the extension, guess I might have to make my own. ^_^

**Comment by cyraid** [comment]
@ArchLeaders For future reference, if you want to have the same code in your registration, you can just add your own extension method:

```csharp
  public static AppBuilder WithIcons(this AppBuilder appBuilder, Action<IconProvider> callback) {
    callback.Invoke(IconProvider.Current);
    return appBuilder;
  } // Function //
```

**Comment by SebastianRumohr** [comment]
I agree that I could have marked the `WithIcons` extension method as obsolete. 
But I didn't want to keep it because with rc1.1 the registration is independent from the `AppBuilder` since the `AvaloniaLocator` has become unavailable.

**Pull request merged**
