### PR TITLE
Added .NET 5 as a valid target

### PR DESCRIPTION
**Pull request by mijgame**
We are building an application with .NET 5, but currently, only .NET Core 3.1 is a valid framework target (which is blocking us).
I haven't seen any issues/breaking changes stemming from this PR.

### CODE REVIEW

**Comment by mijgame** [comment]
Tests seem to fail because .NET 5 is missing there, looking into it.

**Comment by mijgame** [comment]
Tests don't seem to re-run, don't know why

**Comment by SebastianRumohr** [comment]
Hi,
I'm so sorry for my late response. I just missed your pull request. But I'm amazed that you opened one.
Great feature idea. I'll be back in office on monday and reviewing this pull request will be first thing I'll do.

Thank you for your patience. 
Best regards.

**Review by SebastianRumohr — APPROVED** [review]
Will merge it into development and release a new version of the nuget packages afterwards

**Pull request merged**
